<AdicionarVendasPage>:
    FloatLayout:
        canvas:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "icones/bg1.png"

        #Selecionar Cliente
        Label:
            pos_hint: {"right": 1, "top": 1}
            size_hint: 1, 0.05
            text: 'Selecione o Cliente'
            id: selecionar_cliente
        ScrollView:
            pos_hint: {'right': 1, 'top': 0.95}
            size_hint: 1, 0.15
            GridLayout:
                rows: 1
                id: lista_cliente
                size_hint_x: None
                width: self.minimum_width
                spacing: 2, 2
                col_default_width: "100dp"
                col_force_default: True
        #Selecionar Produto
        Label:
            pos_hint: {"right": 1, "top": 0.75}
            size_hint: 1, 0.05
            text: 'Selecione o Produto'
            id: selecionar_produto
        ScrollView:
            pos_hint: {'right': 1, 'top': 0.7}
            size_hint: 1, 0.15
            GridLayout:
                rows: 1
                id: lista_produto
                size_hint_x: None
                width: self.minimum_width
                spacing: 2, 2
                col_default_width: "100dp"
                col_force_default: True
        Label:
            id: label_data
            pos_hint: {"right": 1, "top": 0.5}
            size_hint: 1, 0.05
            bold: True
            text: "01/01/2025"

        #Selecionar Unidade
        GridLayout:
            rows: 1
            pos_hint: {"right": 0.9, "top": 0.45}
            size_hint: 0.8, 0.1
            LabelButton:
                text: "Kg"
                id: unidades_kg
                on_release: app.selecionar_unidades("unidades_kg")
            LabelButton:
                text: "Unidades"
                id: unidades_unidades
                on_release: app.selecionar_unidades("unidades_unidades")
            LabelButton:
                text: "Litros"
                id: unidades_litros
                on_release: app.selecionar_unidades("unidades_litros")

        LabelButton:
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "icones/botao.png" if self.state == 'normal' else "icones/botao_apertado.png"
            on_release: app.mudar_tela("homepage")
            text: "Cancelar"
            pos_hint: {"right": 0.45, "top": 0.2}
            size_hint: 0.4, 0.2

        LabelButton:
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "icones/botao.png" if self.state == 'normal' else "icones/botao_apertado.png"
            on_release: app.adicionar_venda()
            text: "Adicionar Venda"
            pos_hint: {"right": 0.95, "top": 0.2}
            size_hint: 0.4, 0.2


        #Preço Total
        GridLayout:
            rows: 1
            pos_hint: {"right": 0.9, "top": 0.335}
            size_hint: 0.8, 0.075
            Label:
                text: "Preço Total (R$)"
                id: label_preco
            TextInput:
                id: preco_total
                hint_text: "Digite apenas números"
        #Quantidade
        GridLayout:
            rows: 1
            pos_hint: {"right": 0.9, "top": 0.255}
            size_hint: 0.8, 0.075
            Label:
                text: "Quantidade Total"
                id: label_quantidade
            TextInput:
                id: quantidade
                hint_text: "0"
